version: "3.5"

services:
  ew-nginx:
    image: nginx
    hostname: ew-nginx
    container_name: ew-nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./static:/etc/nginx/static
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      - every-wear-network
    depends_on:
      - ew-app

  ew-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ew-app
    hostname: ew-app
    container_name: ew-app
    volumes:
      - ./src:/app/src
      - ./www:/app/www
      - ./app.js:/app/app.js
    ports:
      - "3000:3000"
    networks:
      - every-wear-network
    depends_on:
      - ew-mongodb
      # - ew-mysql

  # ew-mysql:
  #   image: mysql:latest
  #   hostname: ew-mysql
  #   container_name: ew-mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=every-wear-mysql
  #     - MYSQL_DATABASE=every_wear
  #     - MYSQL_USER=every_wear
  #     - MYSQL_PASSWORD=every-wear-mysql!
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   networks:
  #     - every-wear-network

  ew-mongodb:
    image: mongo:4.2
    hostname: ew-mongodb
    container_name: ew-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/cnf:/etc/mongo
      - ./mongodb/log:/var/log/mongodb
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: mongod --auth --config /etc/mongo/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=every-wear-mongo
      - MONGO_INITDB_ROOT_PASSWORD=every-wear-mongo!
      - MONGO_INITDB_DATABASE=every_wear_data
      - TZ=Asia/Seoul
    networks:
      - every-wear-network

networks:
  every-wear-network:
    driver: bridge